[graph]
targets = [
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
]

[advisories]
ignore = []

[licenses]
confidence-threshold = 0.93
private = { ignore = true }
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "bzip2-1.0.6",
    "CC0-1.0",
    "MIT",
    "Unlicense",
    "Unicode-3.0",
    "Zlib",
]
exceptions = []

[bans]
multiple-versions = "warn"
highlight = "all"
skip = []
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [ "https://github.com/rust-lang/crates.io-index" ]
allow-git = []
